services:
  dvwa:
    image: ghcr.io/digininja/dvwa:257b70f
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - lan
    # ports:
    #   - 127.0.0.1:4280:80
    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - lan
    restart: unless-stopped

  waf:
    image: owasp/modsecurity-crs:nginx
    environment:
      - PORT=8080
      - BACKEND=http://dvwa:80
    ports:
      - 127.0.0.1:3000:8080
    networks:
      - lan

volumes:
  dvwa:


networks:
  lan:
    driver: bridge
